"""update profile table

Revision ID: b25f8909a62f
Revises: fa49a16be94d
Create Date: 2026-04-10 00:57:44.633457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b25f8909a62f'
down_revision: Union[str, Sequence[str], None] = 'fa49a16be94d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('is_banned', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.create_unique_constraint('uq_user_email', 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_email', 'user', type_='unique')
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.drop_column('user', 'is_banned')
    op.drop_column('user', 'email')
    op.drop_column('profile', 'age')
    # ### end Alembic commands ###
