"""initial schema

Revision ID: d9ffeeb6444e
Revises: 
Create Date: 2026-02-04 00:09:50.402687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ffeeb6444e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_FirstName'), table_name='user')
    op.drop_column('user', 'FirstName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('FirstName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_user_FirstName'), 'user', ['FirstName'], unique=False)
    # ### end Alembic commands ###
