"""Added Blocked user, users reported, support ticket

Revision ID: fa49a16be94d
Revises: 7cd5ffdbaa84
Create Date: 2026-04-10 00:46:04.395699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fa49a16be94d'
down_revision: Union[str, Sequence[str], None] = '7cd5ffdbaa84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockeduser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('blocked_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_username'], ['user.username'], ),
    sa.ForeignKeyConstraint(['blocker_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supportticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usersreported',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reported_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reported_username'], ['user.username'], ),
    sa.ForeignKeyConstraint(['reporter_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('is_banned', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.drop_column('user', 'is_banned')
    op.drop_column('user', 'email')
    op.drop_table('usersreported')
    op.drop_table('supportticket')
    op.drop_table('blockeduser')
    # ### end Alembic commands ###
